export const appData = {
    dailyFocus: [],
    taskBank: {
        chores: ["Deep Clean House", "Inventory/Restock", "House Tidy", "Pets – Daily"],
        work: ["Instagram – Light", "AI Course – Theory", "Outreach", "Email Wipe"],
        clients: ["Video Client A", "Video Client B", "App Dev Sync"]
    },
    weeklyPlanner: {
        MON: { mission: "Run + Video Client A (Vid 1/1)", length: "1-2 Hours" },
        TUE: { mission: "Gym (Arms/Back/Core) + App Dev", length: "2-3 Hours" },
        WED: { mission: "Run + Video Client B (Vid 1/2)", length: "1-2 Hours" },
        THU: { mission: "Gym (Legs) + App Dev", length: "2-3 Hours" },
        FRI: { mission: "Run + Video Client B (Vid 2/2)", length: "1-2 Hours" },
        SAT: { mission: "Planning & Review + Course Prep", length: "2-4 Hours" },
        SUN: { mission: "Gym (Pilates) + Job/Grant Apps", length: "2 Hours" }
    },
    study: {
        math: { name: "Mathematics", url: "https://www.khanacademy.org/math/" },
        ai: { name: "AI Specialization", url: "https://platform.outskill.com/" },
        lang: { name: "Language Protocol", url: "https://learn.mangolanguages.com/login" },
        write: { name: "Writing Analysis", url: "#" }
    },
    subscriptions: [
        { name: "Perplexity", url: "https://www.perplexity.ai/" },
        { name: "Canva", url: "https://www.canva.com/" },
        { name: "Julius AI", url: "https://julius.ai/" },
        { name: "Lovable", url: "https://lovable.dev" },
        { name: "Lyzr Studio", url: "https://studio.lyzr.ai/" },
        { name: "Fireflies", url: "https://app.fireflies.ai/" },
        { name: "Phot AI", url: "https://www.phot.ai" },
        { name: "Hailuo AI", url: "https://hailuoai.video/" },
        { name: "Vapi", url: "https://dashboard.vapi.ai/" },
        { name: "Writesonic", url: "https://app.writesonic.com/" },
        { name: "HeyGen", url: "https://app.heygen.com/" },
        { name: "Chronicle", url: "https://app.chroniclehq.com/" },
        { name: "Happenstance", url: "https://happenstance.ai/" },
        { name: "MultipleChat", url: "https://multiplechat.ai/" },
        { name: "Wispr Flow", url: "https://wisprflow.ai/" },
        { name: "Retell AI", url: "https://www.retellai.com/" },
        { name: "ElevenLabs", url: "https://elevenlabs.io/" },
        { name: "MeetEmily", url: "https://meetemily.ai/" },
        { name: "Bolt", url: "https://bolt.new/" },
        { name: "LinkedIn", url: "https://www.linkedin.com/" },
        { name: "OpenAI", url: "https://openai.com/" },
        { name: "Pinecone", url: "https://www.pinecone.io/" },
        { name: "n8n", url: "https://n8n.io/" },
        { name: "Dify", url: "https://dify.ai/" },
        { name: "Gumloop", url: "https://www.gumloop.com/" },
        { name: "G-Sheets", url: "https://docs.google.com/spreadsheets" },
        { name: "G-Labs", url: "https://labs.google/" },
        { name: "NotebookLM", url: "https://notebooklm.google/" },
        { name: "Apify", url: "https://apify.com/" },
        { name: "SocialSonic", url: "https://app.socialsonic.com/" },
        { name: "SuperGrow", url: "https://www.supergrow.ai/" },
        { name: "VTurb", url: "https://app.vturb.com/" },
        { name: "Kiwify", url: "https://dashboard.kiwify.com.br/" },
        { name: "GoDaddy", url: "https://dcc.godaddy.com/" },
        { name: "Hotmart", url: "https://app.hotmart.com/" },
        { name: "Atomicat", url: "https://app.atomicat.com.br/" },
        { name: "Supabase", url: "https://supabase.com/dashboard/" },
        { name: "Facebook", url: "https://www.facebook.com/" }
    ]
};